<?php

if (SETTINGS_SITE_LANGUAGE && file_exists(ROOT . 'languages/SDimmersCct_' . SETTINGS_SITE_LANGUAGE . '.php')) {
	include_once(ROOT . 'languages/SDimmersCct_' . SETTINGS_SITE_LANGUAGE . '.php');
} else {
	include_once(ROOT . 'languages/SDimmersCct_default.php'); //
}

$this->device_types['SAqaraBulb'] = array(
	'TITLE' => 'Освещение (Яркость,Температура)',
	'PARENT_CLASS' => 'SControllers',
	'CLASS' => 'SDimmersCct',
	'PROPERTIES' => array(
		'addTimeSunrise' => array('DESCRIPTION' => 'Добавить к восходу(00:00)'),
		'addTimeSunset' => array('DESCRIPTION' => 'Добавить к закат(00:00)'),
		'autoOnOff' => array('DESCRIPTION' => 'Автовключение: 0-не включать 1-включать'),
		'byManually' => array('DESCRIPTION' => 'Включать по заданному времени: 0-Выключить. 1-Включить.', 'ONCHANGE' => 'switchByManually'),
		'bySensor' => array('DESCRIPTION' => 'Включать по датчику света: 0-Отключить. 1-Включить.', 'ONCHANGE' => 'switchBySensor'),
		'bySunTime' => array('DESCRIPTION' => 'Включать по солнцу: 0-Выключить. 1-Включить.', 'ONCHANGE' => 'switchBySunTime'),
		'dayBegin' => array('DESCRIPTION' => 'Начало режима день (hh:mm)'),
		'dayBrightnessLevel' => array('DESCRIPTION' => 'Яркость днем (1<-->brightnessWorkMax)'),
		'dayColorLevel' => array('DESCRIPTION' => 'Температура днем (colorWorkMin<-->colorWorkMax)'),
		'flag' => array('DESCRIPTION' => 'Стопер'),
		'illuminance' => array('DESCRIPTION' => 'Данные с датчика освещения.', 'DATA_KEY' => 1),
		'illuminanceFlag' => array('DESCRIPTION' => 'Стопер датчика освещения'),
		'illuminanceMax' => array('DESCRIPTION' => 'Максимальное освещение.Если меньше включается свет.'),
		'nightBegin' => array('DESCRIPTION' => 'Начало режима ночь (hh:mm)'),
		'nightBrightnessLevel' => array('DESCRIPTION' => 'Яркость ночью(1<-->brightnessWorkMax)'),
		'nightColorLevel' => array('DESCRIPTION' => 'Температура днем (colorWorkMin<-->colorWorkMax)'),
		'presence' => array('DESCRIPTION' => 'Данные с датчика присутствия', 'ONCHANGE' => 'presenceUpdated', 'DATA_KEY' => 1),
		'signSunrise' => array('DESCRIPTION' => 'Прибавить или отнять к/от восхода солнца  1-прибавить, 0-отнять'),
		'signSunset' => array('DESCRIPTION' => 'Прибавить или отнять к/от заката солнца 1-прибавить, 0-отнять'),
		'timerOFF' => array('DESCRIPTION' => 'Задержка перед выключением(секунды). 0-не выключать.'),
		'workInDai' => array('DESCRIPTION' => 'работать: 0-24 часа. 1-Днем. 2-Ночью.'),
		'sunriseTime' => array('DESCRIPTION' => 'Время восхода солнца.'),
		'sunsetTime' => array('DESCRIPTION' => 'Время захода солнца.'),
		'brightnessLevel' => array('DESCRIPTION' => 'Яркость (brightnessWorkMin<-->brightnessWorkMax)', 'ONCHANGE' => 'brightnessLevelChanged', 'DATA_KEY' => 1),
		'brightnessLevelSeved' => array('DESCRIPTION' => 'Сохраненная(предыдущая) яркость.', '_CONFIG_TYPE' => 'num'),
		'brightnessWork' => array('DESCRIPTION' => 'Рабочая температура яркость.', 'ONCHANGE' => 'brightnessWorkChanged', '_CONFIG_TYPE' => 'num'),
		'brightnessWorkMax' => array('DESCRIPTION' => 'Максимальная яркость.', '_CONFIG_TYPE' => 'num'),
		'brightnessWorkMin' => array('DESCRIPTION' => 'Минимальная яркость.', '_CONFIG_TYPE' => 'num'),
		'colorLevel' => array('DESCRIPTION' => 'Цветовая температура: (colorWorkMin<-->colorWorkMax)', 'ONCHANGE' => 'colorLevelChanged', 'DATA_KEY' => 1),
		'colorLevelSeved' => array('DESCRIPTION' => 'Сохраненная(предыдущая) теплота.', '_CONFIG_TYPE' => 'num'),
		'colorWork' => array('DESCRIPTION' => 'Рабочая теплота.', 'ONCHANGE' => 'colorWorkChanged', '_CONFIG_TYPE' => 'num'),
		'colorWorkMax' => array('DESCRIPTION' => 'Максимальная теплота.', '_CONFIG_TYPE' => 'num'),
		'colorWorkMin' => array('DESCRIPTION' => 'Минимальная теплота.', '_CONFIG_TYPE' => 'num'),

	),
	'METHODS' => array(
		'AutoOFF' => array('DESCRIPTION' => 'Автовыключение (timerOFF) 0 не включает.'),
		'brightnessLevelDown' => array('DESCRIPTION' => 'Уменьшить яркость.(array(\'value\'=>1-50)) Без параметров -10.', '_CONFIG_SHOW' => 1, '_CONFIG_REQ_VALUE' => 1),
		'brightnessLevelUp' => array('DESCRIPTION' => 'Увеличить яркость.(array(\'value\'=>1-50)) Без параметров +10.', '_CONFIG_SHOW' => 1, '_CONFIG_REQ_VALUE' => 1),
		'colorLevelDown' => array('DESCRIPTION' => 'Уменьшить температуру.(array(\'value\'=>1-50)) Без параметров -10.', '_CONFIG_SHOW' => 1, '_CONFIG_REQ_VALUE' => 1),
		'colorLevelUp' => array('DESCRIPTION' => 'Увеличить температуру.(array(\'value\'=>1-50)) Без параметров +10.', '_CONFIG_SHOW' => 1, '_CONFIG_REQ_VALUE' => 1),
		'byDefault' => array('DESCRIPTION' => 'Установить свойства по умолчанию.'),
		'colorPreset' => array('DESCRIPTION' => 'Цветовые пресеты.(array(\'value\'=>\'C\'-cold,\'N\'-neutral,\'W\'-warmest))', '_CONFIG_SHOW' => 1, '_CONFIG_REQ_VALUE' => 1),
		'CommandsMenu' => array('DESCRIPTION' => 'Создает меню управления.(Запускать 1 раз для каждого объекта).', '_CONFIG_SHOW' => 1),
		'presenceUpdated' => array('DESCRIPTION' => 'Запускается при изменении свойства presence'),
		'setBrightnessLevel' => array('DESCRIPTION' => 'Установить яркость света.(array(\'value\'=> brightnessWorkMin<-->brightnessWorkMax)) Без  параметров то что в brightnessLevelSeved. Если brightnessLevelSeved пусто то brightnessWorkMax.', '_CONFIG_SHOW' => 1, '_CONFIG_REQ_VALUE' => 1),
		'setColorLevel' => array('DESCRIPTION' => 'Установить температуру.(array(\'value\'=>colorWorkMin <--> colorWorkMax)) Без  параметров то что в colorLevelSeved. Если colorLevelSeved пуст то холодный colorWorkMin.', '_CONFIG_SHOW' => 1, '_CONFIG_REQ_VALUE' => 1),
		'switch' => array('DESCRIPTION' => 'Переключить', '_CONFIG_SHOW' => 1),
		'switchByManually' => array('DESCRIPTION' => 'При включении вручную отключить по солнцу и по датчику.'),
		'switchBySensor' => array('DESCRIPTION' => 'При включении сенсора света отключить по солнцу и вручную.'),
		'switchBySunTime' => array('DESCRIPTION' => 'При включении по солнцу отключить по датчику счета и вручную.'),
		'turnOn' => array('DESCRIPTION' => 'ВключитЬ', '_CONFIG_SHOW' => 1),
		'turnOff' => array('DESCRIPTION' => 'Выключить', '_CONFIG_SHOW' => 1),
		'brightnessLevelChanged' => array('DESCRIPTION' => 'Запускается при смене яркости'),
		'colorLevelChanged' => array('DESCRIPTION' => 'Запускается при смене цвета температуры'),
		'brightnessWorkChanged' => array('DESCRIPTION' => 'Запускается при смене рабочей яркости'),
		'colorWorkChanged' => array('DESCRIPTION' => 'Запускается при смене цвета рабочей температуры'),
	),
);
